Add SWTH token
osmosis-labs/assetlists pull request #112
Opened 2022-02-23 03:54 UTC by RavenXce

Hi, reopening this to resolve merge conflicts.

There was a previous confusion about base denoms. Please note that our unit / base denom (0 exponent) is `swth` on source chain. `dswth` a new denom with 8 exponent for display use. 

---

IBC tx: https://www.mintscan.io/osmosis/txs/89AEB65A1D7F67E8785A55427C6D9B37E24540F26389EBF6DD2FC6EE31183297

Balances:
```
osmosisd query bank balances osmo1t6tveyjtmcf54p56yrd9x48vecu94fyf6wytxe
balances:
- amount: "428888888"
  denom: ibc/8FEFAE6AECF6E2A255585617F781F35A8D5709A545A804482A261C0C9548A9D3
- amount: "100131476"
  denom: uosmo
pagination:
  next_key: null
  total: "0"
```

2022-03-03 04:09 UTC, RavenXce commented
Hi @IbrarMakaveli, is this ok to merge?

2022-03-03 17:53 UTC, IbrarMakaveli requested changes

2022-03-03 17:53 UTC, IbrarMakaveli commented on osmosis-1/osmosis-1.assetlist.json
> +          "denom": "SWTH",
"denom": "swth",

2022-03-03 17:53 UTC, IbrarMakaveli commented on osmosis-1/osmosis-1.assetlist.json
> +      "display": "SWTH",
"display": "swth",

2022-03-05 19:41 UTC, IbrarMakaveli approved these changes

2022-03-15 01:26 UTC, merged