Added DOKI
osmosis-labs/assetlists pull request #1130
Opened 2024-02-19 09:26 UTC by AddySiz

## Description

 Adding DOKI from Odin chain

## Checklist

### Adding Assets

If adding a new asset, please ensure the following:
- [ ] Asset is registered to the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).
   - The `description` and/or `extended_description` of the asset in the Chain Registry is informative.
- [ ] Add asset to bottom of `zone_assets.json`.
   - The IBC channel referenced in `path` must be registered to the Chain Registry.
   - `osmosis_unlisted` defaults to `true` (until the respesentation and transferring of the new asset has been validated)
   - Note that it is recommended to include an X (fka, Twitter) profile URL with each asset.

### On-chain liquidity

For each new asset, please provide the plan for on-chain liquidity of the asset: (choose one)
- [ ] Ready -- A liquidity pool has been created. The pool ID is: ______
- [ ] Soon -- A pool will be created. (See: [Pool Setup Guilde](https://docs.osmosis.zone/overview/integrate/pool-setup).)
  - [ ] (optional) A preview of the Osmosis Zone app with the new asset added is requested for creating the pool. (Supercharged Liquidity pools cannot be created via Osmosis Zone app)
- [ ] StreamSwap -- The token is, or will be, going through a StreamSwap stream; thus, the token should be listed without requiring on-chain liquidity. A Pool ID will be provided in this PR following the stream's completion once the team has had a chance to create a pool using the earned funds.

2024-02-20 05:44 UTC, danbryan commented on osmosis-1/osmosis-1.assetlist.json
> +            "channel_id": "channel-3"
/
```suggestion
            "channel_id": "channel-74"
```

2024-02-20 05:45 UTC, danbryan commented on osmosis-1/osmosis-1.assetlist.json
> +            "channel_id": "channel-258",
```suggestion
            "channel_id": "channel-20925",
```

2024-02-20 05:45 UTC, danbryan commented on osmosis-1/osmosis-1.assetlist.json
> +            "path": "transfer/channel-258/udoki"
```suggestion
            "path": "transfer/channel-20925/udoki"
```

2024-02-20 05:46 UTC, danbryan requested changes
updated channels for doki request

2024-02-20 06:13 UTC, danbryan commented on osmosis-1/osmosis-1.assetlist.json
> +          "denom": "ibc/C12C353A83CD1005FC38943410B894DBEC5F2ABC97FC12908F0FB03B970E8E1B",
```suggestion
          "denom": "ibc/BADB06C54ADD5BC4C8B74982F961CB0287BAE326E799FCD8D03387EB8BB7D550",
```

2024-02-20 07:18 UTC, Satchitananda commented on osmosis-1/osmosis.zone_assets.json
> +      ]
@AddySiz remove this line

2024-03-12 17:35 UTC, JeremyParish69 commented on osmosis-1/osmosis.zone_assets.json
> +
Please remove this extra line

2024-03-12 17:36 UTC, JeremyParish69 commented on osmosis-1/osmosis.zone_assets.json
> +      },
Please take out on indent here for proper formatting

2024-03-12 17:36 UTC, JeremyParish69 commented on osmosis-1/osmosis-1.assetlist.json
> +    {
Please do not update the assetlist.json file directly

2024-03-12 17:39 UTC, JeremyParish69 commented on osmosis-1/osmosis.zone_assets.json
> +      "twitter_URL": "https://twitter.com/doki_coin",
Could you please Register this (and a website if there is one) to the Cosmos Chain Registry?
It is not required for listing, but it is become part of the 'Verified' status upgrade process.

2024-03-12 17:41 UTC, merged

2024-03-12 21:45 UTC, JeremyParish69 commented
Please update once Pool ID is known.

Also, see the latest updates on Verified process: https://github.com/osmosis-labs/assetlists/blob/main/LISTING.md