Added Marble DAO CW20 from JUNO
osmosis-labs/assetlists pull request #116
Opened 2022-03-04 09:16 UTC by the0developer

2022-03-05 19:36 UTC, IbrarMakaveli requested changes

2022-03-05 19:36 UTC, IbrarMakaveli commented on osmosis-1/osmosis-1.assetlist.json
> +        "png": "https://raw.githubusercontent.com/osmosis-labs/assetlists/main/images/marble-logo.png"
`        "png": "https://raw.githubusercontent.com/osmosis-labs/assetlists/main/images/marble.png"
`
Also can you rename image -> marble.png

2022-03-06 00:46 UTC, dylanschultzie approved these changes

2022-03-06 02:02 UTC, the0developer reviewed
@IbrarMakaveli Done, it should be good. Thanks for taking the time

2022-03-07 08:59 UTC, sunnya97 commented on osmosis-1/osmosis-1.assetlist.json
> +          ]
```suggestion
          "exponent": 0
```

2022-03-07 09:01 UTC, sunnya97 commented
Please add back coingecko after price is served from coingecko

2022-03-07 13:26 UTC, the0developer commented
> Please add back coingecko after price is served from coingecko

I'll do it Sunny, thanks.

2022-03-08 17:25 UTC, IbrarMakaveli approved these changes

2022-03-08 17:25 UTC, merged