Add Gravity Bridge DAI, ETH, USDC, USDT
osmosis-labs/assetlists pull request #123
Opened 2022-03-19 14:11 UTC by jkilpatr

This commit adds metadata for major Ethereum tokens brought to Osmosis
over Gravity Bridge. This will allow users of these pools to see the
token name and decimals.

2022-03-21 12:32 UTC, ankurdotb approved these changes

2022-04-06 21:40 UTC, ChristianBorst commented on osmosis-1/osmosis-1.assetlist.json
> +        "png": "https://raw.githubusercontent.com/osmosis-labs/assetlists/main/images/usdc.png",
Change to usdt.png/svg images

2022-04-06 21:40 UTC, ChristianBorst commented on osmosis-1/osmosis-1.assetlist.json
> +        "png": "https://raw.githubusercontent.com/osmosis-labs/assetlists/main/images/usdc.png",
Change to dai.png/svg images

2022-04-06 21:43 UTC, ChristianBorst commented on osmosis-1/osmosis-1.assetlist.json
> +      "png": "https://cerberus-chain.s3.us-east-2.amazonaws.com/main/crbrus.png"
Remove this line

2022-04-06 21:51 UTC, jkilpatr commented on osmosis-1/osmosis-1.assetlist.json
> +      "png": "https://cerberus-chain.s3.us-east-2.amazonaws.com/main/crbrus.png"
thanks for flagging resolved.

2022-04-06 21:51 UTC, jkilpatr commented on osmosis-1/osmosis-1.assetlist.json
> +        "png": "https://raw.githubusercontent.com/osmosis-labs/assetlists/main/images/usdc.png",
thanks for flagging resolved.

2022-04-06 21:52 UTC, jkilpatr commented on osmosis-1/osmosis-1.assetlist.json
> +        "png": "https://raw.githubusercontent.com/osmosis-labs/assetlists/main/images/usdc.png",
thanks for flagging resolved.

2022-04-08 16:41 UTC, ankurdotb approved these changes

2022-04-08 20:56 UTC, IbrarMakaveli requested changes
Can you switch your token PR on assetlist frontier : `osmosis-frontier.assetlist.json`
Thanks !

2022-04-15 18:31 UTC, jkilpatr commented
closed in favor of #144

2022-04-15 18:31 UTC, closed without merging