Sifchain: adding Rowan asset to the osmosis-1 network asset list.
osmosis-labs/assetlists pull request #27
Opened 2021-10-05 15:46 UTC by gzukel

Added Rowan.

2021-10-12 13:39 UTC, IbrarMakaveli commented on osmosis-1/osmosis-1.assetlist.json
> +      "symbol": "ROWAN",
```suggestion
      "name": "Sifchain",
      "symbol": "ROWAN",
```

2021-10-13 15:55 UTC, gzukel commented
@IbrarMakaveli Thanks for the changes. Applied. Appreciate it.

2021-10-13 16:42 UTC, IbrarMakaveli requested changes

2021-10-13 16:42 UTC, IbrarMakaveli commented on osmosis-1/osmosis-1.assetlist.json
> +        "png": "https://raw.githubusercontent.com/osmosis-labs/assetlists/main/images/rowan.png"
```suggestion
        "png": "https://raw.githubusercontent.com/osmosis-labs/assetlists/main/images/rowan.png",
```

2021-10-17 11:09 UTC, sunnya97 commented
Moving to #33  to fix merge conflicts

2021-10-17 11:25 UTC, sunnya97 commented on osmosis-1/osmosis-1.assetlist.json
> +          "exponent": 10,
Guys, I'm pretty sure this is wrong.  Doesn't rowan use 18 decimal points of precission.

2021-10-17 23:25 UTC, closed without merging