Decentr native token
osmosis-labs/assetlists pull request #97
Opened 2022-02-13 01:02 UTC by megaherz

2022-02-13 01:04 UTC, megaherz commented
```
osmosisd query bank balances osmo12c2mwfzvn2cy462zarr7yg8yj9l8n76mmeckea
balances:
- amount: "1019998"
  denom: ibc/9BCB27203424535B6230D594553F1659C77EC173E36D9CF4759E7186EE747E84
- amount: "35935090"
  denom: uosmo
pagination:
  next_key: null
  total: "0"
```

IBC received transaction https://www.mintscan.io/osmosis/txs/3546CB671464C82AA1D2A2F746D927344CCDE81784DC17066C39473B02D0C74B

2022-02-15 04:18 UTC, IbrarMakaveli requested changes

2022-02-15 04:18 UTC, IbrarMakaveli commented on osmosis-1/osmosis-1.assetlist.json
> +          "denom": "udec",
"denom": "dec",

2022-02-15 04:18 UTC, IbrarMakaveli commented on osmosis-1/osmosis-1.assetlist.json
> +        "svg": "https://raw.githubusercontent.com/osmosis-labs/assetlists/main/images/decentr.svg"
"png": "https://raw.githubusercontent.com/osmosis-labs/assetlists/main/images/dec.png",
        "svg": "https://raw.githubusercontent.com/osmosis-labs/assetlists/main/images/dec.svg"

2022-02-15 06:21 UTC, megaherz commented on osmosis-1/osmosis-1.assetlist.json
> +          "denom": "udec",
Thx, fixed

2022-02-15 06:22 UTC, megaherz commented on osmosis-1/osmosis-1.assetlist.json
> +        "svg": "https://raw.githubusercontent.com/osmosis-labs/assetlists/main/images/decentr.svg"
Renamed

2022-02-16 06:07 UTC, megaherz commented
Sorry, incorrectly rebased, created a new one https://github.com/osmosis-labs/assetlists/pull/103

2022-02-16 06:07 UTC, closed without merging